apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: notificationserver
  name: notificationserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notificationserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/backend-backend: "true"
        io.kompose.service: notificationserver
    spec:
      containers:
        - image: tinajassik/notification-server:latest
          name: notificationserver
          ports:
            - containerPort: 5016
              hostPort: 5016
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
